version: "3.8"
services:
  microapp:
    build: .
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: "npm run serve"
